name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Create test file
        run: |
          cd lib
          touch test_file.dart
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add -A
          git commit -m "Add file"
          git tag v1.0.0
          git push origin v1.0.0 
